version: '3.7'

services:
  dev:
    image: williamjackson/pelican:4.2.0
    command:
      - --autoreload
      - --listen
    ports:
      - 8000:8000

  clean:
    image: williamjackson/pelican:4.2.0
    entrypoint:
      - /bin/rm
    command:
      - -f
      - -r
      - __pycache__
      - cache
      - output
